### ISSUE TITLE
PandocLuaError "Cannot get Attr from TypeNil"

### ISSUE THREAD

**Issue by lbluque** [openjournals/inara#11]
Hello, 

I was attempting to compile a manuscript prior to submission using the docker image following the docs
```
docker run --rm \
    --volume $PWD/paper:/data \
    --user $(id -u):$(id -g) \
    --env JOURNAL=joss \
    openjournals/inara
```

But ran into this error,
```
Error running filter /usr/local/share/openjournals/data/filters/normalize-metadata.lua:
PandocLuaError "Cannot get Attr from TypeNil"
stack traceback:
        ...l/share/openjournals/data/filters/normalize-metadata.lua:95: in function 'Meta'
```

Seems like the same error reported in the Github Action a few months back in openjournals/openjournals-draft-action#6

**Comment by tarleb** [comment]
Thank you for the report. Please post a minimal `paper.md` that allows us to reproduce the error -- otherwise it is difficult to investigate this. Also, please make sure that you are using the latest image version by running `docker pull openjournals/inara`.

**Comment by lbluque** [comment]
Ah indeed. I tested the latest version with the sample paper in the docs and there is no issue. For my case I had an incorrect format for the title section.

Thanks @tarleb
