### ISSUE TITLE
Empty metadata time values

### ISSUE THREAD

**Issue by xuanxu** [openjournals/inara#2]
When using inara to create a draft, `published_at` metadata will have no value, and sometimes `submitted_at` will also be empty.
Now when any of these values are null or an empty string this error [is happening](https://github.com/openjournals/joss-papers-testing/runs/4366044371?check_suite_focus=true#step:3:116) in the [time filter](https://github.com/openjournals/inara/blob/main/data/filters/time.lua#L21-L22):
```bash
[INFO] Running filter /usr/local/share/openjournals/data/filters/time.lua
Error running filter /usr/local/share/openjournals/data/filters/time.lua:
/usr/local/share/openjournals/data/filters/time.lua:8: bad argument #1 to 'for iterator' (table expected, got string)
stack traceback:
	[C]: in function 'next'
	/usr/local/share/openjournals/data/filters/time.lua:8: in upvalue 'copy_string_values'
	/usr/local/share/openjournals/data/filters/time.lua:21: in function 'Meta'
```

Inara should accept nil `published_at`/`submitted_at` values and compile the paper with an empty value there.

**Comment by tarleb** [comment]
Made a view changes that should fix this. We still require the values to be set, but now provide default values.
