### ISSUE TITLE
orcid missing https base URL in generated JATS XML

### ISSUE THREAD

**Issue by castedo** [openjournals/inara#24]
I think code in this repository is generating the JATS XML in `openjournals/joss-papers` which has orcid content values which do not include the base URL `https://orcid.org/`. For example:
https://github.com/openjournals/joss-papers/blob/c5d4302e65b0d2135b5c70efb9bff3a23b4b1a8a/joss.04611/10.21105.joss.04611.jats

This is inconsistent with what appears in the JATS XML files in the PMC Open Data Set, e.g.:
ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/84/fc/PMC9293011.tar.gz
and eLife JATS XML files: e.g.
https://github.com/elifesciences/elife-article-xml/blob/master/articles/elife-77625-v1.xml
These existing JATS XML styles include the `https://orcid.org/`. Per https://en.wikipedia.org/wiki/ORCID: "Formally, ORCID IDs are specified as URIs". Looks like formally not including the https base URL results in a [International Standard Name Identifier](https://en.wikipedia.org/wiki/International_Standard_Name_Identifier) (ISNI) and not an ORCID.

**Comment by tarleb** [comment]
You're right, that should be fixed.

**Comment by castedo** [comment]
FWIW, I made the same mistake with my own JATS XML and have already archived JATS XML files in archive.softwareheritage.org. I just assumed the base URL should not be included. Seems odd to me the current standard.

I now have gitlab.com/perm.pub/epijats outputing HTML and PDF that properly handles either style in the JATS XML that is read.
