### ISSUE TITLE
Additional latex packages

### ISSUE THREAD

**Issue by fnattino** [openjournals/inara#28]
Hi there! I am writing a manuscript for JOSS (draft [here](https://github.com/GO-Eratosthenes/dhdt/blob/master/paper/paper.md)), for which I would like to use a package that is not part of the latex installation within the Inara image (the [`dirtree`](https://www.ctan.org/pkg/dirtree) package).

Is there a way to include additional latex packages before generating PDFs via the Inara container? If not, would you consider to include `dirtree` in the list of packages that are installed with `tlmgr` in the image?

**Comment by tarleb** [comment]
Hi @fnattino! Unfortunately, I'm afraid that the requirements for Inara render this change difficult to the point that's it's probably unfeasible.

Inara currently produces three outputs from the `paper.md`, one of which we can ignore here. The other two are PDF and JATS XML. The latter is a standardized archiving format that should contain the same contents as the PDF. For unsupported packages, this means that new logic would have to be added to translate LaTeX input to JATS. It's certainly possible, but it requires time that's may have a bigger impact when spent on other issues.

This is why I'd suggest one of the two following alternatives:

1. Include the file the as code that was generated with the `tree` utility:

    ```
    src
    ├── test.sh
    └── unicorn.txt
    ```

2. Generate a PDF "image" on a local computer and include it as a figure `![caption text](path/to/file.pdf)`. The `standalone` LaTeX documentclass can often be very handy for that purpose.

**Comment by fnattino** [comment]
@tarleb thank you very much for the quick reply and for the alternative solutions - I will likely implement the first one!  Thanks!
