### ISSUE TITLE
Loading more latex packages

### ISSUE THREAD

**Issue by saeedmhz** [openjournals/inara#31]
Is the a way that I can load bbm package?

I need to have '$\mathbbm{1}$' in my paper.

**Comment by tarleb** [comment]
One can use `$\pmb{𝟙}$` for the time being. However, we are considering to use a different method for PDF rendering in the future (ConTeXt), which would cause this to stop working. I would suggest to use glyphs that are available as Unicode characters if possible, e.g. 𝟙 or 𝟏.

**Comment by saeedmhz** [comment]
Thanks for the response.
I actually figured \mathbb{1} outputs 𝟙 in my case.
