### ISSUE TITLE
lualatex error: Undefined control sequence on \citeproc when generating pdf from the example

### ISSUE THREAD

**Issue by zhanghe9704** [openjournals/inara#41]
When generating pdf from the example, I got the following error: 

> [INFO] [makePDF] LaTeX run number 1
Latexmk: Run number 1 of rule 'lualatex'
Collected error summary (may duplicate other messages):
  lualatex: Command for 'lualatex' gave return code 1
      Refer to '/tmp/tex2pdf.-7470bf7304835743/input.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
[INFO] [makePDF] LaTeX output
  This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian)
   restricted system commands enabled.
Error producing PDF.
! Undefined control sequence.
l.403 Software (\citeproc

I'm using Ubuntu 20.04. My pandoc version is 3.1.11.1, installed from a deb file.

**Comment by darthoctopus** [comment]
This is because pandoc 3.1.11 changes how CSL references are handled. I've made a branch with the relevant changes cross-ported here: https://github.com/darthoctopus/inara . However, a pull request isn't feasible because no new Docker images for pandoc with latex have been released for close to a year now, and these changes are not backwards-compatible (and so will break Docker support at the moment).

**Comment by zhanghe9704** [comment]
Thanks for the fast response. I tested it again on the example. This time, I got "Undefined control sequence" on \NewDocumentCommand. Please see the following log:

> [INFO] [makePDF] LaTeX run number 1
Latexmk: Run number 1 of rule 'lualatex'
Collected error summary (may duplicate other messages):
  lualatex: Command for 'lualatex' gave return code 1
      Refer to '/tmp/tex2pdf.-fc7b4a80903bc34a/input.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
[INFO] [makePDF] LaTeX output
  This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian)
   restricted system commands enabled.
Error producing PDF.
! Undefined control sequence.
l.69 \NewDocumentCommand

**Comment by zhanghe9704** [comment]
I downgraded the pandoc to version 3.0. Now I can compile the example file using the inara code from main branch.
