### ISSUE TITLE
small unicode error?

### ISSUE THREAD

**Issue by arjunsavel** [openjournals/inara#43]
Hi! When downloading tex files for, e.g., arxiv submission, I notice that a unicode error doesn't get appropriately written to tex (í --> ı́ ). Various tex compilers break to various degrees (pdflatex on Overleaf doesn't complain too much, arxiv breaks completely) unless the offending characters are replaced. Happy to provide more info or move this issue to a more appropriate repo!

**Comment by tarleb** [comment]
> I notice that a unicode error doesn't get appropriately written to tex (í --> ı́)

I'm not sure I understand. Do you mean "unicode character", and could you add more information about what you're seeing versus what you'd expect the output to be?

**Comment by tarleb** [comment]
The issue still isn't clear to me, waiting for clarification. Closing until then.
