### ISSUE TITLE
Incompatible with pandoc >=3.1.7

### ISSUE THREAD

**Issue by sneakers-the-rat** [openjournals/inara#44]
Trying to run using the makefile, and getting

```
Error producing PDF.
! Undefined control sequence.
l.403 Software (\citeproc
```

searching around leads here: https://tex.stackexchange.com/questions/695228/undefined-control-sequence-using-citeproc-to-convert-md-to-pdf-with-a-template
then here: https://github.com/jgm/pandoc/issues/9031#issuecomment-1694744040

which was apparently merged in 3.1.7

will PR in the moment with fix, but ya the dependencies section in the readme needs a little love <3

**Comment by tarleb** [comment]
Fix via #52.
