### ISSUE TITLE
make preprint target broken 

### ISSUE THREAD

**Issue by musoke** [openjournals/inara#48]
README.md says

https://github.com/openjournals/inara/blob/0739fb5f750a900ef917b973c18f239aafacb1fd/README.md?plain=1#L46-L53

As far as I can tell this is not accurate. Running
```
$ make preprint ARTICLE=joss/paper.md
```
results in the error
```
make: *** No rule to make target 'publishing-artifacts/paper-preprint.tex', needed by 'preprint'.  Stop.
```
and no `.tex` file is written to `publication_artifacts`.

The analogous docker command does work.

**Comment by tarleb** [comment]
Thanks for the report. Should be fixed now.

**Comment by tarleb** [comment]
Please note that the `Makefile` is not as well maintained as the Docker file. We might remove it in the future.

**Comment by musoke** [comment]
Thanks you!
