### ISSUE TITLE
Change tests to use latex instead of PDF

### ISSUE THREAD

**Issue by cthoyt** [openjournals/inara#81]
Right now, the tests look at the PDF binaries. It would be more meaningful to diff the underlying latex that created these PDFs. Therefore I propose the following:

1. Add a new configuration for creating the latex file
2. Swap out the PDF tests for latex files

**Comment by tarleb** [comment]
This makes *a lot* of sense for testing, but I also seem to remember that we intentionally don't provide a way to generate LaTeX output. I think it's because users should be using `preprint` instead.

We should keep a test to make sure that the PDF still compiles ok.

**Comment by cthoyt** [comment]
Agreed that we can keep a test that the PDF compiles okay, that's currently being handled by the `example-doc.yml` workflow, which is completely separate from the `make test` portion of the `build.yaml` workflow.

The only issue is if we don't test the PDF directly, then we won't have a mechanism of testing the changes to the underlying document. So it might be possible to make an update to the preprint template that doesn't have a corresponding update in the default template.
