### ISSUE TITLE
Bug in affiliations XML

### ISSUE THREAD

**Issue by xuanxu** [openjournals/inara#92]
Digging the cause of [this error](https://github.com/openjournals/joss-reviews/issues/6939#issuecomment-2432340123) I suspect some recent change when adding support for ROR is involved:
There is a problem with the generated Crossref XML file: The affiliation field [includes](https://github.com/openjournals/joss-papers/pull/6043/commits/8287a0137060b3439043058854c8b02f4990f6d4#diff-5cf05587c0495e737ad19373b00e1d0ae4f92db4f942216d7ef427430e89d13eR49) an `affiliation_name` that looks is not valid (as per [crossref 5.3.1](https://www.crossref.org/schemas/crossref5.3.1.xsd))

cc/ @cthoyt

**Comment by cthoyt** [comment]
I’m afk for the evening but I am quite confident that the updates follow the crossref spec as stated. The implementation came from following their documentation - I would never have come up with such a convoluted data structure myself 😁

will take a look tomorrow morning CET

**Comment by cthoyt** [comment]
Is it possible there’s a difference in the crossref validation done by joss and Inara’s test suite?

**Comment by arfon** [comment]
/ cc @tarleb too for visibility

**Comment by xuanxu** [comment]
[This PR](https://github.com/openjournals/inara/pull/93) should fix the errors.

In the meantime and until we have a new release I'm making the build to use Inara v1.1.1
