### ISSUE TITLE
Newlines inserted in the title in the metadata files

### ISSUE THREAD

**Issue by xuanxu** [openjournals/inara#96]
The generated crossref and JATS files include the paper's title adding a newline in the middle (see for example [a generated file](https://github.com/openjournals/joss-papers/pull/6201/files#diff-03b7cec5851a145bce786cc69b8cc410c593d8d357f212e52c4403929016b742R40-R42) or [the metadata in crossref](https://api.crossref.org/works/10.21105/joss.06889)). When adding records to ORCID, there is no space in the place of the newlines.
@tarleb Is this an error or a line-width requirement from crossref/JATS? Can we get rid of the newlines?

**Comment by tarleb** [comment]
Makes sense, I pushed a fix.

**Comment by xuanxu** [comment]
Thanks! I've created a v1.1.5 release and updated the GitHub action.
